# Generated by Django 5.0.3 on 2024-04-07 13:14

import django.db.models.deletion
import main.models._user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_email_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='friend_friend_group', to='main.friendgroup'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('admins', models.ManyToManyField(related_name='chat_admins', to='main.user')),
                ('members', models.ManyToManyField(related_name='chat_members', to='main.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_chat', to='main.chat')),
                ('read_users', models.ManyToManyField(related_name='chat_message_read_users', to='main.user')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message_reply_to', to='main.chatmessage')),
                ('sender', models.ForeignKey(on_delete=models.SET(main.models._user.User.magic_user_deleted), related_name='chat_message_sender', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserChatRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('unread_after', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_relation_chat', to='main.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_relation_user', to='main.user')),
            ],
        ),
    ]
