# Generated by Django 5.0.3 on 2024-05-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chatinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_users',
            field=models.ManyToManyField(related_name='chat_message_deleted_users', to='main.user'),
        ),
    ]
